project:
  type: website
  output-dir: _site

website:
  title: "Computational Marketing | University of Liverpool"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: teaching.qmd
        text: Teaching
      - href: research.qmd
        text: Research
      - href: demos.qmd
        text: Demos
    right:
      - icon: github
        href: https://github.com

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: true

execute:
  freeze: auto
