services:
  - type: web
    name: uol-churn-predictor
    runtime: python
    rootDir: apps/churn_predictor
    buildCommand: pip install -r ../../requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
